name: Process CSV Data
on:
  workflow_dispatch:
  push:
    paths:
      - '*.csv'

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Using the published action
      - name: Process CSV File
        uses: ssghait007/resumable-action@v4
        id: resumable-action
        with:
          csv-file: 'sample.csv'
          processing-script: 'process_script.py'
          artifact-retention-days: 2

      # Access the last processed index
      - name: Check Progress
        run: |
          echo "Last processed index: ${{ steps.resumable-action.outputs.last-processed }}"